### ISSUE TITLE
View my Invoice

### ISSUE THREAD

**Issue by vekerdyb** [dangerfarms/tf-app#10]
As a User
I want to view my Invoices
So that I see what was I paid for a given job

**Details**
The views should be added in invoices/views.py  
Use generic django rest framework views where possible.
RetrieveAPIView should do the job fine. 
No custom serializer should be necessary for this task.

**Tasks**

API:
- [ ] Create InvoiceDetail view that uses the builtin RetrieveAPIView
- [ ] serve the view from /invoices/[invoice_id]

Client:
[coming soon]

**AC**
API:
- [ ] should get given invoice on /invoices/[invoice_id] if logged in
- [ ] should get 401 if not logged in
- [ ] should not allow changing the model via POST/PUT/PATCH requests
- [ ] should get 401 if logged in but invoice does not belong to the logged in user

Client: 
[coming soon]
