### ISSUE TITLE
View list of Projects

### ISSUE THREAD

**Issue by vekerdyb** [dangerfarms/tf-app#11]
As a User
I want to view a list of Projects
So that I can see what work is available

**Details**
The views should be added in projects/views.py  
Use generic django rest framework views where possible.
ListAPIView should do the job fine. 
No custom serializer should be necessary for this task.

**Tasks**

API:
- [ ] Create ProjectList view that uses the builtin ListAPIView
- [ ] serve the view from /projects/

Client:
[coming soon]

**AC**
API:
- [ ] should get the list of Projects on /projects/ if logged in
- [ ] should get 401 on /projects/ if not logged in
- [ ] should not allow POST/PUT/PATCH requests

Client: 
[coming soon]
