### ISSUE TITLE
View Project details

### ISSUE THREAD

**Issue by vekerdyb** [dangerfarms/tf-app#12]
As a User
I want to view Project details
So that I can understand the context of each project

**Details**
The views should be added in projects/views.py  
The serializers should be added in projects/serializers.py  

Use generic django rest framework views where possible.
RetrieveAPIView should do the job fine. 
Create a custom serializer that adds a new field: `active`, which is calculated as follows: start date is passed, end date has not passed. The field value should be Boolean.

**Tasks**

API:
- [ ] Create ProjectDetail view that uses the builtin RetrieveAPIView
- [ ] create ProjectDetail serializer with active field and all other existing fields
- [ ] serve the view from /projects/[project_id]

Client:
[coming soon]

**AC**
API:
- [ ] should get project on /projects/[project_id] if logged in and project exists
- [ ] should get 401 if not logged in
- [ ] should not allow changing the model via POST/PUT/PATCH requests
- [ ] should return active field
- [ ] should set active to true if current date is between start and end date
- [ ] should set active to false if current date is not between start and end date

Client: 
[coming soon]
