### ISSUE TITLE
View a list of my currently active Tasks

### ISSUE THREAD

**Issue by vekerdyb** [dangerfarms/tf-app#16]
As a Developer
I want to view my currently active Tasks
So I can quickly get to them

**Details**
The views should be added in tasks/views.py  
ListAPIView should do the job fine. 
Set the queryset of the view to return only that belong to the logged in user.
The filter should be created in tasks/filters.py  

There should be filtering available to show only active (start date passed, end date not reached) tasks.
Make use of DRF filters, more specifically: http://www.django-rest-framework.org/api-guide/filtering/#custom-generic-filtering

**Tasks**

API:
- [ ] Create MyTaskList view that uses the builtin ListAPIView
- [ ] Create an ActiveTask filter
- [ ] serve the view from /tasks/assigned/

Client:
[coming soon]

**AC**
API:
- [ ] should get the list of Tasks that are assigned to the logged in user on /tasks/assigned/ if logged in
- [ ] should not return tasks that are assigned to someone else or unassigned
- [ ] should get 401 on the url if not logged in
- [ ] should not allow POST/PUT/PATCH requests
- [ ] should return only active tasks if `active=true` parameter is specified in the request (suggestion: test by adding 3 tasks, one that hasn't started yet, one that is already finished, and one that is active, and test that only the active one is returned)
- [ ] should return only not active tasks if `active=false` is specified

Client: 
[coming soon]
