### ISSUE TITLE
View all available Tasks

### ISSUE THREAD

**Issue by vekerdyb** [dangerfarms/tf-app#17]
As a Developer
I want to view all available Tasks
So I spend less time browsing for Tasks to take

**Details**
The views should be added in tasks/views.py  
ListAPIView should do the job fine. 
Set the queryset of the view to return only that are not assigned to anyone, and are active (current date is between start_date and end_date, not closed).

**Tasks**

API:
- [ ] Create AvailableTasks view that uses the builtin ListAPIView
- [ ] serve the view from /tasks/available/

Client:
[coming soon]

**AC**
API:
- [ ] should get the list of Tasks that are assigned to no-one on /tasks/available/ if logged in
- [ ] should not return inactive tasks (current date not between start_date and end_date)
- [ ] should not return closed tasks
- [ ] should not return tasks that are assigned to someone
- [ ] should get 401 on the url if not logged in
- [ ] should not allow POST/PUT/PATCH requests

Client: 
[coming soon]
