### ISSUE TITLE
View details of a Task

### ISSUE THREAD

**Issue by vekerdyb** [dangerfarms/tf-app#18]
As a Developer
I want to view specific details of a Task
So that I can make a decision on whether to take it on

**Details**
The views should be added in tasks/views.py  
The serializers should be added in tasks/serializers.py  

RetrieveAPIView should do the job fine. 
Create a custom serializer that adds a new field: `active`, which is calculated as follows: start date is passed, end date has not passed. The field value should be Boolean.

**Tasks**

API:
- [ ] Create TaskDetail view that uses the builtin RetrieveAPIView
- [ ] create TaskDetail serializer with calculated active field and all other existing fields of the model
- [ ] serve the view from /tasks/[task_id]

Client:
[coming soon]

**AC**
API:
- [ ] should get task details on /tasks/[task_id] if logged in and the task exists
- [ ] should get 401 if not logged in
- [ ] should not allow changing the model via POST/PUT/PATCH requests
- [ ] should return active field
- [ ] should set active to true if current date is between start and end date
- [ ] should set active to false if current date is not between start and end date

Client: 
[coming soon]
