### ISSUE TITLE
View my Profile

### ISSUE THREAD

**Issue by vekerdyb** [dangerfarms/tf-app#8]
As a User
I want to view my profile
So that I can overview my details

**Details**

**Tasks**
Client:
- 
API:
- [ ] Create ProfileDetail view
- [ ] Create ProfileDetail serializer
- [ ] serve the view from /users/[user_name]

**AC**
- [ ] should get user's profile on /users/[user_name] if logged in
- [ ] should get 404 on user's profile if not logged in
