### ISSUE TITLE
View list of Profiles

### ISSUE THREAD

**Issue by vekerdyb** [dangerfarms/tf-app#9]
As a User
I want to view a list of user profiles
So that I can see everyone on the system in one view

**Details**
The views should be added in profiles/views.py  
Use generic django rest framework views where possible.
ListAPIView should do the job fine. 
No custom serializer should be necessary for this task.

**Tasks**

API:
- [ ] Create ProfileList view that uses the builtin ListAPIView
- [ ] serve the view from /users/

Client:
[coming soon]

**AC**
API:
- [ ] should get the list of user's profile on /users/ if logged in
- [ ] should get 404 on /users/ if not logged in
- [ ] should not allow POST/PUT/PATCH requests

Client: 
[coming soon]
